### PR TITLE
feat: Added region in router

### PR DESCRIPTION
**Pull request by AshutoshAM2002**
## what
* Added region in router because it was depends on region in provider.

### CODE REVIEW

**Comment by Tanveer143s** [comment]
Create workflows 
Ref: https://github.com/clouddrove/terraform-gcp-kms/tree/feat/issue-11/.github/workflows

**Comment by AshutoshAM2002** [comment]
> Create workflows Ref: https://github.com/clouddrove/terraform-gcp-kms/tree/feat/issue-11/.github/workflows

Done

**Review by theprashantyadav — COMMENTED** [review]
@AshutoshAM2002 Please fix tflint warning

**Comment by VishwajitNagulkar** [comment]
Plz add latest example in readme.yml
https://github.com/clouddrove/terraform-gcp-subnet/blob/fix/router/README.yaml

**Comment by AshutoshAM2002** [comment]
> Plz add latest example in readme.yml https://github.com/clouddrove/terraform-gcp-subnet/blob/fix/router/README.yaml

Done

**Review by VishwajitNagulkar — APPROVED** [review]
LGTM

**Review by theprashantyadav — APPROVED** [review]
LGTM!

**Pull request merged**
